# Generated by Django 5.0.7 on 2024-08-02 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_user_avatar"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="avatar",
            new_name="avatar_url",
        ),
    ]
